openapi: 3.0.0
info:
  title: Event Service
  version: 1.0
  description: |
       **Note :**
              Please note that the partial updates are supported via PUT APIs. However, Note that If "null" value is passed for any element, in the PUT request body, it will be ignored. An empty string value should be sent (instead of "null" value) for the elements that need to be updated with NULL values.
servers:
  - url: 'https://api.hslynk.com/event-service/rest/'
paths:
  "/clients/{clientid}subscriptions":
    parameters:
      - name: clientid
        in: path
        required: true
        schema:
          type: string
        description: Client Identifier
    post:
      responses:
        '200':
          description: OK 
          content:
            application/json:
              example: |

      description: |
      operationId: POST_subscription
      requestBody:
        content:
          application/json:
              schema:
                properties:
                    type:
                        type: string
                required:
                - type
                type: object
              example:
                    type: COVID
        required: true            